### ISSUE TITLE
Recursive read lock acquisitions not allowed in this mode.

### ISSUE THREAD

**Issue by VictorioBerra** [IzyPro/WatchDog#137]
**Description**
```
   at System.Threading.ReaderWriterLockSlim.TryEnterReadLockCore(TimeoutTracker timeout)
   at System.Threading.ReaderWriterLockSlim.TryEnterReadLock(TimeSpan timeout)
   at LiteDB.Engine.LockService.EnterTransaction()
   at LiteDB.Engine.TransactionMonitor.GetTransaction(Boolean create, Boolean queryOnly, Boolean&amp; isNew)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.Engine.LiteEngine.Insert(String collection, IEnumerable`1 docs, BsonAutoId autoId)
   at LiteDB.LiteCollection`1.Insert(T entity)
   at WatchDog.src.Helpers.LiteDBHelper.InsertWatchLog(WatchLog log)
   at WatchDog.src.Managers.DynamicDBManager.InsertWatchLog(WatchLog log)
   at WatchDog.src.WatchDog.InvokeAsync(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
   at WatchDog.src.WatchDogExceptionLogger.InvokeAsync(HttpContext context)
```

**To Reproduce**
I started a new .NET 8 project and added WatchDog and I get these errors everywhere.

**Expected behavior**
No LiteDB errors?

**Screenshots**

**Details (please complete the following information):**
 - Project Type: Razor Pages
 - Framework Version .NET 8
 - WatchDog Version 1.4.10
 - Database LiteDB 
 - Browser Chrome

**Additional context**

**Comment by VictorioBerra** [comment]
Bump.

**Comment by VictorioBerra** [comment]
Bump

**Comment by Khelechy** [comment]
Update to 1.40.11
