### ISSUE TITLE
OutOfMemoryException

### ISSUE THREAD

**Issue by alan841207** [IzyPro/WatchDog#75]
Hello   I Response file Stream , OutOfMemoryException .Can you add a setting, too large streams will not load
2022-11-07 16:44:02.2718 [Error] [0] Microsoft.AspNetCore.Diagnostics.DiagnosticsLoggerExtensions.UnhandledException : An unhandled exception has occurred while executing the request. System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Text.StringBuilder.ToString()
   at System.IO.StreamReader.ReadToEndAsyncInternal()
   at WatchDog.src.WatchDog.LogResponse(HttpContext context)
   at WatchDog.src.WatchDog.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

**Comment by IzyPro** [comment]
Hi @alan841207 
This has been resolved in the just released v1.3.3
